### ISSUE TITLE
1-second timer value does not work

### ISSUE THREAD

**Issue by LanceNorskog** [tagomoris/fluent-plugin-numeric-monitor#11]
When I use the numeric_monitor plugin with a timer value of 1 second, it fires every two seconds.
This is the config block I use:

<match stats.**>
    type numeric_monitor
     aggregate tag
     input_tag_remove_prefix stats
     tag_prefix stats2
     monitor_key count
     count_interval 1s
     output_per_tag yes
</match>

This posts a new output every 2 seconds, and the counts add up. So it's running every 2 seconds instead of every second. 

Is this supposed to work? Does Ruby support sub-second timers? If not, please make it an error to use 1 second.

**Comment by tagomoris** [comment]
Fixed this bug and released `v0.1.8`.
@LanceNorskog Please reopen this issue if you still have problems!
